export type Dealer = {
  name: string;
  address: string;
  location: string;
  type: "Showroom";
  lat: number;
  lng: number;
};

export const dealers: Dealer[] = [
  {
    name: "Safaa Building Materials Trading L.L.C",
    address: "10 17th Street - Umm Ramool - Al Rashidiya - Dubai",
    location: "https://maps.app.goo.gl/QqatAj4XA8tiBXQz7",
    type: "Showroom",
    lat: 25.2368044,
    lng: 55.3660817,
  },
  {
    name: "Aqua World Building Materials Trading LLC (Branch 1)",
    address: "199 Umm Suqeim St - Al Qouz Ind.fourth - Al Quoz - Dubai",
    location: "https://maps.app.goo.gl/PqGDEByuEqGtnJnW7",
    type: "Showroom",
    lat: 25.1094668,
    lng: 55.2229542,
  },
  // {
  //   name: "Jalal Sons DHA Phase 4",
  //   address: "151 Street 1, DHA Phase 4 Sector DD Dha Phase 4, Lahore",
  //   location: "https://maps.app.goo.gl/sndunVRqUvfxSCeA8",
  //   type: "Showroom",
  //   lat: 31.46215260359395,
  //   lng: 74.3660817,
  // },
  {
    name: "Aqua World Building Materials Trading LLC (Branch 2)",
    address: "Al Qouz Ind.third - Al Quoz - Dubai",
    location: "https://maps.app.goo.gl/7j3hfSDDLAEfLbks9",
    type: "Showroom",
    lat: 25.1130019,
    lng: 55.2183172,
  },
  {
    name: "Jasi Building Materials LLC Main Shop",
    address: "22 27th St - Al Qouz Ind.third - Al Quoz - Dubai",
    location: "https://maps.app.goo.gl/9T7J5TAo6qwny97b7",
    type: "Showroom",
    lat: 25.1173233,
    lng: 55.2131451,
  },
  {
    name: "New Qamar Jasi Building Materials Trading LLC (Branch 1)",
    address: "Al Qouz Ind.third - Al Quoz - Dubai",
    location: "https://maps.app.goo.gl/pujP9wuaPEhhNokF7",
    type: "Showroom",
    lat: 25.1184364,
    lng: 55.2128443,
  },
  {
    name: "Laspinas Building Materials Trading (Main Shop)",
    address:
      "First Al Khail St Jamal Al Gurair Building, Warehouse #07 Block F, Plot 368-448 - Dubai",
    location: "https://maps.app.goo.gl/d1f1DXWm68ctDeQj8",
    type: "Showroom",
    lat: 25.1319349,
    lng: 55.2185505,
  },
  {
    name: "Royal Apex Building Materials Trading LLC",
    address: "Warehouse # 1 - Al Qouz Ind.third - Dubai",
    location: "https://maps.app.goo.gl/HRG6PyAzLB6CD6hx8",
    type: "Showroom",
    lat: 25.1214969,
    lng: 55.2215383,
  },
  {
    name: "Reality Building Materials Trading LLC (Noor Al Hutaib Trading LLC)",
    address: "390396 - near Emirates Glass - Al Qouz Ind.fourth - Dubai",
    location: "https://maps.app.goo.gl/nfC2B78mftjvGJGC7",
    type: "Showroom",
    lat: 25.1154858,
    lng: 55.2243815,
  },
  {
    name: "Faza Home Building Materials (Branch 1)",
    address:
      "Ind 3 - 4 9a St - Al Quoz - Al Quoz Industrial Area 3 - Shop #11 - First Al Khail St - Al Quoz - Dubai",
    location: "https://maps.app.goo.gl/uaAJ53KbnR5gf5S39",
    type: "Showroom",
    lat: 25.132954,
    lng: 55.2166367,
  },
  {
    name: "Smooth Solution Building Materials Trading LLC (Branch 1)",
    address: "Besides Emirates Glass - Al Qouz Ind.third - Al Quoz - Dubai",
    location: "https://maps.app.goo.gl/VM2uzut4mYYr3LTL7",
    type: "Showroom",
    lat: 25.1139861,
    lng: 55.2251135,
  },
  {
    name: "Smooth Solution Building Materials Trading LLC (Branch 2)",
    address: "24 Street 5b - Al Qouz Ind.first - Al Quoz - Dubai",
    location: "https://maps.app.goo.gl/zEAiz2affK4Kwqdu6",
    type: "Showroom",
    lat: 25.137,
    lng: 55.233,
  },
  {
    name: "New Qamar Al Huda Building Materials Trading LLC (Branch 1)",
    address: "33 28B Street - Al Qouz Ind.third - Al Quoz - Dubai",
    location: "https://maps.app.goo.gl/38oyNyEvB2B7HUF2A",
    type: "Showroom",
    lat: 25.1184048,
    lng: 55.2210658,
  },
  {
    name: "New Qamar Al Huda Building Materials Trading LLC (Branch 2)",
    address: "27th St - Al Qouz Ind.third - Al Quoz - Dubai",
    location: "https://maps.app.goo.gl/4FeBJ9kgSDhUBMDm7",
    type: "Showroom",
    lat: 25.1189085,
    lng: 55.2139911,
  },
  {
    name: "Al Junaibi Building Materials Trading LLC (Branch 3)",
    address: "25 11 B St - Opposite Aramex - Al Qouz Ind.first - Al Quoz - Dubai",
    location: "https://maps.app.goo.gl/p2jFmeViNu23tYTs8?g_st=aw",
    type: "Showroom",
    lat: 25.1385,
    lng: 55.232,
  },
  {
    name: "New Qamar Al Jasi Building Materials Trading LLC (Branch 3)",
    address:
      "Warehouse-4 - near Pepsi Roundabout - Dubai Investment Park Second - Dubai",
    location: "https://maps.app.goo.gl/pRbD4caxqF7tkr1X9",
    type: "Showroom",
    lat: 24.972364,
    lng: 55.1961099,
  },
  {
    name: "New Qamar Al Sahra Building Materials Trading LLC (Branch 2)",
    address: "Dubai Investment Park - 1 - Dubai",
    location: "https://maps.app.goo.gl/qgePoa4xq2quHg9w5",
    type: "Showroom",
    lat: 25.1899452,
    lng: 55.0923234,
  },
  {
    name: "Redha Farhan Trdg. LLC",
    address: "6GC3+6X2 - Al Khawaneej - Al Khwaneej Second - Dubai",
    location: "https://maps.app.goo.gl/qSqGQAGYqvPYhV6LA",
    type: "Showroom",
    lat: 25.2205286,
    lng: 55.5023259,
  },
  {
    name: "Qamar Al Sahra Building Materials Trading LLC (Branch 1)",
    address: "Al Manama St - Ras Al Khor Ind. Second - 2 Ras Al Khor - Dubai",
    location: "https://maps.app.goo.gl/fNFnjb2CawjEdqgFA",
    type: "Showroom",
    lat: 25.190384,
    lng: 55.0923228,
  },
  {
    name: "Team Trading Co. LLC",
    address: "77 Al Ittihad Rd - Port Saeed - Deira - Dubai",
    location: "https://maps.app.goo.gl/Jo8UNzkYcq3sxoHm7",
    type: "Showroom",
    lat: 25.2583559,
    lng: 55.3264366,
  },
  {
    name: "Al Mushtari Building Materials LLC",
    address: "Al Hudaiba Rd - Al Bada' - Dubai",
    location: "https://maps.app.goo.gl/bJaJqCGxNmzSvSsPA",
    type: "Showroom",
    lat: 25.2292519,
    lng: 55.2738551,
  },
  {
    name: "Afreen Building Materials Trading Co. LLC",
    address: "9GG5+FXP - Musaffah - M9 - Abu Dhabi",
    location: "https://maps.app.goo.gl/wK819wTwRFiP3Wkz9",
    type: "Showroom",
    lat: 24.376415,
    lng: 54.5072905,
  },
  {
    name: "Apex Trading",
    address:
      "Apex Trading Co WLL BR, Musaffah Industrial - 119 Al Jazzeem St - Musaffah - M10 - Abu Dhabi",
    location: "https://maps.app.goo.gl/RQU1i8nGYL7Pz11Y6",
    type: "Showroom",
    lat: 24.3724643,
    lng: 54.5018262,
  },
  {
    name: "Brightway Trading LLC (Branch 1)",
    address: "Musaffah - Musaffah Industrial - Abu Dhabi",
    location: "https://maps.app.goo.gl/Hngd5P1FofboHt3b8",
    type: "Showroom",
    lat: 24.3541717,
    lng: 54.4988761,
  },
  {
    name: "Royal Rajab Trading Company",
    address:
      "Najda street,Next to National Hospital(Behind Honda Showroom - Abu Dhabi",
    location: "https://maps.app.goo.gl/DdbZJFc6jaL1AGiC6",
    type: "Showroom",
    lat: 24.4903535,
    lng: 54.3729666,
  },
  {
    name: "Faza Sanitary Ware Trading LLC (Branch 2)",
    address:
      "Industrial Area 6 (and near Al Ghuwair Market / Rolla area), Sharjah, UAE",
    location: "https://maps.app.goo.gl/aw3t36Se7npBkWM8A",
    type: "Showroom",
    lat: 25.3592875,
    lng: 55.3902246,
  },
  {
    name: "Aqua Arab Trading Co. LLC (Branch 3)",
    address:
      "Street 69 - opposite Al Khowahir Chemicals - Industrial Area 2 - Industrial Area - Sharjah",
    location: "https://maps.app.goo.gl/USk7FtbaU9sUjN2j7",
    type: "Showroom",
    lat: 25.3125564,
    lng: 55.4071826,
  },
  {
    name: "Aqua Arab Trading Co. LLC (Branch 4)",
    address: "Shop# 1,2,Sheikh Khalid building - Sharjah",
    location: "https://maps.app.goo.gl/N6HmQBZ6wzCpReMu5",
    type: "Showroom",
    lat: 25.3601985,
    lng: 55.3932934,
  },
  {
    name: "Naja Sanitary Ware Trading Co. LLC",
    address: "Al Ghuwair - Hay Al Gharb - Sharjah",
    location: "https://maps.app.goo.gl/uM9G3RhBAF6RTpUEA",
    type: "Showroom",
    lat: 25.3589369,
    lng: 55.3935609,
  },
  {
    name: "Jernas Building Materials Trading LLC (Branch 1)",
    address: "Julfar - Ras Al Khaimah",
    location: "https://maps.app.goo.gl/8uov6ML2Zroz5NVKA",
    type: "Showroom",
    lat: 25.769672,
    lng: 55.83479,
  },
  {
    name: "Jernas Building Materials Trading LLC (Branch 2)",
    address: "Sheikh Mohammed Bin Zayed Rd - Al Riffa - Ras Al Khaimah",
    location: "https://maps.app.goo.gl/oQVoHeK6tcT2spJZ6",
    type: "Showroom",
    lat: 25.7135701,
    lng: 55.8465601,
  },
  {
    name: "Salma Sanitary Trading",
    address: "Jiddah St - Al Jerf Industrial 3 - Ajman",
    location: "https://maps.app.goo.gl/DJaeEKGisa2REDp69",
    type: "Showroom",
    lat: 25.4330134,
    lng: 55.5419806,
  },
];
